version: '3.8'
services:
  app:
    container_name: web-app
    restart: always
    build: .
    ports:
      - '8888:3000'
    links:
      - mongo
    environment:
      DB_SERVER: mongo
      DB_PORT: 27017
      PORT: 3000

  mongo:
    container_name: mongo
    image: mongo:4.1.6
    ports:
      - '27017:27017'
